services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: iufp_postgres
    environment:
      POSTGRES_DB: iufp_rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iufp_local_2025
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql
    restart: unless-stopped

volumes:
  postgres_data: